{% set build = 0 %}
{% set version = "2.4.1" %}

package:
    name: tig
    version: {{version}}

about:
    home: https://github.com/jonas/tig/
    license: GPLv2
    summary: ncurses-based Git repository browser

source:
    fn: tig-{{version}}.tar.gz
    url: https://github.com/jonas/tig/releases/download/tig-{{version}}/tig-{{version}}.tar.gz
    md5: 9a7c31ea2c83a5cd0c65c275c4d671db

requirements:
    build:
        - asciidoc
        - ncurses
        - readline
    run:
        - ncurses
        - readline

build:
    number: {{build}}
